version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
